                
name: CI/CD-bymaw04o4g
on: 
  push:
 
jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         image: [v-y8tgk4rcur,v-9uggs4n2sy]
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image without explicit login
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: buildimage/${{matrix.image}}:latest
      - name: Verify the built image (optional)
        run: docker image ls

  build-image-v02:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         image: [v-ohi1ulpv0u,v-dkqjd2t1pk]
    continue-on-error: true
    needs: build-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image without explicit login
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: buildimage/${{matrix.image}}:latest
      - name: Verify the built image (optional)
        run: docker image ls

  build-image-v03:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         image: [v-0zrxmohbtz,v-kya77v16gu]
    continue-on-error: true
    needs: build-image-v02
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image without explicit login
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: buildimage/${{matrix.image}}:latest
      - name: Verify the built image (optional)
        run: docker image ls

  build-image-v04:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
         image: [v-6smmje3ktl,v-epc5ejs8jb]
    continue-on-error: true
    needs: build-image-v03
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image without explicit login
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: buildimage/${{matrix.image}}:latest
      - name: Verify the built image (optional)
        run: docker image ls
